spring.application.name=LibraryAPI
spring.datasource.url=jdbc:postgresql://localhost:5433/library_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update

application.security.secret-key=9a111be4912681959835f22fa7ab73974d221ca281bb3f356a484f0a359b7c1b