name: Test Self-Hosted Runner
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - run: echo "Bu komut, VM'in kendi üzerinde çalışıyor!" && hostname && whoami